# Sklearn NMF - Rough Way

In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
import os
import librosa as lb
import soundfile as sf
from sklearn.decomposition import NMF

In [3]:
path = "/home/rajesh/Desktop/Datasets/Saraga3stem/train/Aaniraimekkani/"

### Data Processing

In [4]:
files = os.listdir(path)
files

['vocals.wav',
 'violin.wav',
 'mixture.wav',
 'mridangam.wav',
 'accompaniment.wav']

In [5]:
m, m_fs = sf.read(path+'mixture.wav')
b1, b1_fs = sf.read(path+'mridangam.wav')
b2, b2_fs = sf.read(path+'vocals.wav')
b3, b3_fs = sf.read(path+'violin.wav')

In [6]:
print(m_fs, b1_fs, b2_fs, b3_fs)

44100 44100 44100 44100


In [7]:
print(len(m), len(b1), len(b2), len(b3))

12661103 12661103 12661103 12661103


In [8]:
b1 = b1[:12661103]
b2 = b2[:12661103]
b3 = b3[:12661103]
m = m[:12661103]

In [10]:
print(len(m), len(b1), len(b2), len(b3))

12661103 12661103 12661103 12661103


### Model

In [11]:
B = np.array([b1, b2, b3])

In [12]:
b = b1 + b2 + b3

In [13]:
difference = b - m

In [14]:
dot = np.dot(b, m)
dot

-1015.8340366780758

In [15]:
difference.shape

(12661103,)

In [16]:
B_mag = np.abs(B)

In [17]:
model = NMF(n_components=3, init='random', random_state=0)
W = model.fit_transform(B_mag)
H = model.components_

In [18]:
W

array([[0.00030418, 0.0741612 , 0.        ],
       [0.11468899, 0.        , 0.00103566],
       [0.        , 0.00089241, 0.09152173]])

### Writting Output

In [19]:
out_path = "/home/rajesh/Desktop/"

In [284]:
sf.write(out_path+'Emridangam.wav', H[0], 44100) #Estimated
sf.write(out_path+'Evocals.wav', H[1], 44100)
sf.write(out_path+'Eviolin.wav', H[2], 44100)

##### writting non-negative audios

In [21]:
sf.write(out_path+'Amridangam.wav', np.abs(b1), 44100) #Absolute Original
sf.write(out_path+'Avocals.wav', np.abs(b2), 44100)
sf.write(out_path+'Aviolin.wav', np.abs(b3), 44100)

In [22]:
sf.write(out_path+'Omridangam.wav', b1, 44100) #Original
sf.write(out_path+'Ovocals.wav', b2, 44100)
sf.write(out_path+'Oviolin.wav', b3, 44100)

In [23]:
b1 == np.abs(b1)

array([False, False, False, ...,  True,  True, False])

In [24]:
b1

array([-1.52587891e-03, -1.77001953e-03, -1.46484375e-03, ...,
        9.15527344e-05,  9.15527344e-05, -1.83105469e-04])